/**
 * Morok client crypto.
 *
 * Identity:
 * - Seed: 256 bits CSPRNG.
 * - Mnemonic: BIP39 English wordlist, 24 words.
 * - Ed25519 keypair (signing).
 *
 * Encryption (1-on-1 DM):
 * - X25519 keypair derived from same seed.
 * - ECDH → shared secret.
 * - HKDF-SHA256 → 32-byte symmetric key.
 * - XChaCha20-Poly1305 with random 24-byte nonce.
 * - Format: nonce(24) ‖ ciphertext+tag → base64.
 *
 * Encryption (group):
 * - Each group has a 32-byte symmetric `group_key` generated by the creator.
 * - Same group_key is distributed to new members via DM (kind=group_key).
 * - Group name and every group message are XChaCha20-Poly1305 with the
 *   group_key and a fresh random 24-byte nonce.
 * - Same wire format as DM: nonce(24) ‖ ct+tag → base64.
 *
 * Forward secrecy: NOT YET — same DH key per peer-pair, same group_key
 * for the life of the group. OK for MVP because relay holds messages 24h.
 */

import { ed25519, edwardsToMontgomeryPub, x25519 } from '@noble/curves/ed25519';
import { sha256 } from '@noble/hashes/sha256';
import { sha512 } from '@noble/hashes/sha512';
import { hkdf } from '@noble/hashes/hkdf';
import { randomBytes } from '@noble/hashes/utils';
import { xchacha20poly1305 } from '@noble/ciphers/chacha';
import {
  entropyToMnemonic,
  mnemonicToEntropy,
  validateMnemonic,
} from '@scure/bip39';
import { wordlist } from '@scure/bip39/wordlists/english';

// ────────────────────────────────────────────────────────────
// Bytes / encoding helpers
// ────────────────────────────────────────────────────────────

export function bytesToHex(bytes) {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

export function hexToBytes(hex) {
  if (typeof hex !== 'string' || hex.length % 2 !== 0) {
    throw new Error('hex must be even-length string');
  }
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export function bytesToBase64(bytes) {
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

export function base64ToBytes(b64) {
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

export function utf8(s) { return new TextEncoder().encode(s); }
export function utf8Decode(b) { return new TextDecoder().decode(b); }

// ────────────────────────────────────────────────────────────
// Identity
// ────────────────────────────────────────────────────────────

export function generateIdentity() {
  const seed = randomBytes(32);
  const mnemonic = entropyToMnemonic(seed, wordlist);
  const pubkey = ed25519.getPublicKey(seed);
  return { seed, mnemonic, pubkeyHex: bytesToHex(pubkey) };
}

export function identityFromMnemonic(mnemonic) {
  const cleaned = mnemonic.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!validateMnemonic(cleaned, wordlist)) {
    throw new Error('Невалідна 24-словна фраза');
  }
  const seed = mnemonicToEntropy(cleaned, wordlist);
  const pubkey = ed25519.getPublicKey(seed);
  return { seed, mnemonic: cleaned, pubkeyHex: bytesToHex(pubkey) };
}

// ────────────────────────────────────────────────────────────
// Signing (Ed25519)
// ────────────────────────────────────────────────────────────

export function sign(seed, messageBytes) {
  return bytesToHex(ed25519.sign(messageBytes, seed));
}

export function canonicalJson(obj) {
  return utf8(JSON.stringify(obj, Object.keys(obj).sort()));
}

export function signAuthChallenge({ seed, pubkeyHex, challengeHex, timestamp }) {
  const msg = canonicalJson({
    morok_auth: 'v1',
    challenge: challengeHex,
    pubkey: pubkeyHex,
    timestamp,
  });
  return sign(seed, msg);
}

export function signEnvelope({ seed, fromHex, toHex, ts, ttl, blobB64 }) {
  const msg = canonicalJson({
    blob: blobB64,
    from: fromHex,
    to: toHex,
    ts,
    ttl,
  });
  return sign(seed, msg);
}

// ────────────────────────────────────────────────────────────
// Key derivation (X25519 from Ed25519 seed)
// ────────────────────────────────────────────────────────────

function x25519PrivFromSeed(seed) {
  const h = sha512(seed);
  const k = h.slice(0, 32);
  k[0] &= 248;
  k[31] &= 127;
  k[31] |= 64;
  return k;
}

function x25519PubFromEd25519Pub(edPubBytes) {
  return edwardsToMontgomeryPub(edPubBytes);
}

export function deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex }) {
  const myX25519Priv = x25519PrivFromSeed(seed);
  const peerEdPub = hexToBytes(peerPubkeyHex);
  const peerX25519Pub = x25519PubFromEd25519Pub(peerEdPub);
  const sharedSecret = x25519.getSharedSecret(myX25519Priv, peerX25519Pub);

  const myEd = hexToBytes(myPubkeyHex);
  const meFirst = myPubkeyHex < peerPubkeyHex;
  const a = meFirst ? myEd : peerEdPub;
  const b = meFirst ? peerEdPub : myEd;
  const salt = new Uint8Array(64);
  salt.set(a, 0);
  salt.set(b, 32);

  return hkdf(sha256, sharedSecret, salt, utf8('morok-dm-v1'), 32);
}

// ────────────────────────────────────────────────────────────
// Encrypt / Decrypt (XChaCha20-Poly1305) — DM
// ────────────────────────────────────────────────────────────

export function encryptForPeer({ seed, myPubkeyHex, peerPubkeyHex, plaintext }) {
  const key = deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex });
  const nonce = randomBytes(24);
  const cipher = xchacha20poly1305(key, nonce);
  const ct = cipher.encrypt(utf8(plaintext));
  const out = new Uint8Array(24 + ct.length);
  out.set(nonce, 0);
  out.set(ct, 24);
  return bytesToBase64(out);
}

export function decryptFromPeer({ seed, myPubkeyHex, peerPubkeyHex, blobB64 }) {
  const raw = base64ToBytes(blobB64);
  if (raw.length < 40) throw new Error('blob too short');
  const nonce = raw.slice(0, 24);
  const ct = raw.slice(24);
  const key = deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex });
  const cipher = xchacha20poly1305(key, nonce);
  const pt = cipher.decrypt(ct);
  return utf8Decode(pt);
}

// ────────────────────────────────────────────────────────────
// Symmetric encrypt / decrypt (XChaCha20-Poly1305) — groups
// ────────────────────────────────────────────────────────────

/**
 * Generate a fresh 32-byte symmetric key (used as group_key).
 */
export function generateSymmetricKey() {
  return randomBytes(32);
}

/**
 * Encrypt arbitrary bytes with a known 32-byte symmetric key.
 * Output: nonce(24) ‖ ciphertext+tag, base64.
 */
export function encryptWithKey(keyBytes, plaintextBytes) {
  if (keyBytes.length !== 32) throw new Error('key must be 32 bytes');
  const nonce = randomBytes(24);
  const cipher = xchacha20poly1305(keyBytes, nonce);
  const ct = cipher.encrypt(plaintextBytes);
  const out = new Uint8Array(24 + ct.length);
  out.set(nonce, 0);
  out.set(ct, 24);
  return bytesToBase64(out);
}

/**
 * Decrypt blob produced by encryptWithKey. Returns Uint8Array.
 * Throws if key wrong (auth tag fails).
 */
export function decryptWithKey(keyBytes, blobB64) {
  if (keyBytes.length !== 32) throw new Error('key must be 32 bytes');
  const raw = base64ToBytes(blobB64);
  if (raw.length < 40) throw new Error('blob too short');
  const nonce = raw.slice(0, 24);
  const ct = raw.slice(24);
  const cipher = xchacha20poly1305(keyBytes, nonce);
  return cipher.decrypt(ct);
}

/**
 * Convenience: encrypt a UTF-8 string with symmetric key. Returns base64 blob.
 */
export function encryptStringWithKey(keyBytes, plaintext) {
  return encryptWithKey(keyBytes, utf8(plaintext));
}

/**
 * Convenience: decrypt blob to UTF-8 string.
 */
export function decryptStringWithKey(keyBytes, blobB64) {
  return utf8Decode(decryptWithKey(keyBytes, blobB64));
}
