/**
 * Morok client crypto.
 *
 * Identity:
 * - Seed: 256 bits CSPRNG.
 * - Mnemonic: BIP39 English wordlist, 24 words.
 * - Ed25519 keypair (signing).
 *
 * Encryption (1-on-1 DM):
 * - X25519 keypair derived from same seed.
 * - ECDH → shared secret.
 * - HKDF-SHA256 → 32-byte symmetric key.
 * - XChaCha20-Poly1305 with random 24-byte nonce.
 * - Format: nonce(24) ‖ ciphertext+tag → base64.
 *
 * Encryption (group):
 * - Each group has a 32-byte symmetric `group_key` generated by the creator.
 * - Same group_key is distributed to new members via DM (kind=group_key).
 * - Group name and every group message are XChaCha20-Poly1305 with the
 *   group_key and a fresh random 24-byte nonce.
 * - Same wire format as DM: nonce(24) ‖ ct+tag → base64.
 *
 * Forward secrecy: NOT YET — same DH key per peer-pair, same group_key
 * for the life of the group. OK for MVP because relay holds messages 24h.
 */

import { ed25519, edwardsToMontgomeryPub, x25519 } from '@noble/curves/ed25519';
import { sha256 } from '@noble/hashes/sha256';
import { sha512 } from '@noble/hashes/sha512';
import { hkdf } from '@noble/hashes/hkdf';
import { randomBytes } from '@noble/hashes/utils';
import { xchacha20poly1305 } from '@noble/ciphers/chacha';
import {
  entropyToMnemonic,
  mnemonicToEntropy,
  validateMnemonic,
} from '@scure/bip39';
import { wordlist } from '@scure/bip39/wordlists/english';

// ────────────────────────────────────────────────────────────
// Bytes / encoding helpers
// ────────────────────────────────────────────────────────────

export function bytesToHex(bytes) {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

export function hexToBytes(hex) {
  if (typeof hex !== 'string' || hex.length % 2 !== 0) {
    throw new Error('hex must be even-length string');
  }
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export function bytesToBase64(bytes) {
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

export function base64ToBytes(b64) {
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

export function utf8(s) { return new TextEncoder().encode(s); }
export function randomBytesSafe(n) { return randomBytes(n); }
export function sha256Bytes(b) { return sha256(b); }
export function utf8Decode(b) { return new TextDecoder().decode(b); }

// ────────────────────────────────────────────────────────────
// Identity
// ────────────────────────────────────────────────────────────

export function generateIdentity() {
  const seed = randomBytes(32);
  const mnemonic = entropyToMnemonic(seed, wordlist);
  const pubkey = ed25519.getPublicKey(seed);
  return { seed, mnemonic, pubkeyHex: bytesToHex(pubkey) };
}

/**
 * Відновлює ті самі 24 слова з seed (seed == BIP39 entropy).
 * Детерміновано: один і той самий seed завжди дає ту саму мнемоніку.
 * seed може бути Uint8Array або hex-рядком.
 */
export function mnemonicFromSeed(seed) {
  const bytes = typeof seed === 'string' ? hexToBytes(seed) : seed;
  return entropyToMnemonic(bytes, wordlist);
}

export function identityFromMnemonic(mnemonic) {
  const cleaned = mnemonic.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!validateMnemonic(cleaned, wordlist)) {
    throw new Error('Невалідна 24-словна фраза');
  }
  const seed = mnemonicToEntropy(cleaned, wordlist);
  const pubkey = ed25519.getPublicKey(seed);
  return { seed, mnemonic: cleaned, pubkeyHex: bytesToHex(pubkey) };
}

// ────────────────────────────────────────────────────────────
// Signing (Ed25519)
// ────────────────────────────────────────────────────────────

export function sign(seed, messageBytes) {
  return bytesToHex(ed25519.sign(messageBytes, seed));
}

export function canonicalJson(obj) {
  return utf8(JSON.stringify(obj, Object.keys(obj).sort()));
}

export function signAuthChallenge({ seed, pubkeyHex, challengeHex, timestamp }) {
  const msg = canonicalJson({
    morok_auth: 'v1',
    challenge: challengeHex,
    pubkey: pubkeyHex,
    timestamp,
  });
  return sign(seed, msg);
}

export function signEnvelope({ seed, fromHex, toHex, ts, ttl, blobB64 }) {
  const msg = canonicalJson({
    blob: blobB64,
    from: fromHex,
    to: toHex,
    ts,
    ttl,
  });
  return sign(seed, msg);
}

// ────────────────────────────────────────────────────────────
// Key derivation (X25519 from Ed25519 seed)
// ────────────────────────────────────────────────────────────

function x25519PrivFromSeed(seed) {
  const h = sha512(seed);
  const k = h.slice(0, 32);
  k[0] &= 248;
  k[31] &= 127;
  k[31] |= 64;
  return k;
}

function x25519PubFromEd25519Pub(edPubBytes) {
  return edwardsToMontgomeryPub(edPubBytes);
}

export function deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex }) {
  const myX25519Priv = x25519PrivFromSeed(seed);
  const peerEdPub = hexToBytes(peerPubkeyHex);
  const peerX25519Pub = x25519PubFromEd25519Pub(peerEdPub);
  const sharedSecret = x25519.getSharedSecret(myX25519Priv, peerX25519Pub);

  const myEd = hexToBytes(myPubkeyHex);
  const meFirst = myPubkeyHex < peerPubkeyHex;
  const a = meFirst ? myEd : peerEdPub;
  const b = meFirst ? peerEdPub : myEd;
  const salt = new Uint8Array(64);
  salt.set(a, 0);
  salt.set(b, 32);

  return hkdf(sha256, sharedSecret, salt, utf8('morok-dm-v1'), 32);
}

// ────────────────────────────────────────────────────────────
// Encrypt / Decrypt (XChaCha20-Poly1305) — DM
// ────────────────────────────────────────────────────────────

export function encryptForPeer({ seed, myPubkeyHex, peerPubkeyHex, plaintext }) {
  const key = deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex });
  const nonce = randomBytes(24);
  const cipher = xchacha20poly1305(key, nonce);
  const ct = cipher.encrypt(utf8(plaintext));
  const out = new Uint8Array(24 + ct.length);
  out.set(nonce, 0);
  out.set(ct, 24);
  return bytesToBase64(out);
}

export function decryptFromPeer({ seed, myPubkeyHex, peerPubkeyHex, blobB64 }) {
  const raw = base64ToBytes(blobB64);
  if (raw.length < 40) throw new Error('blob too short');
  const nonce = raw.slice(0, 24);
  const ct = raw.slice(24);
  const key = deriveSharedKey({ seed, myPubkeyHex, peerPubkeyHex });
  const cipher = xchacha20poly1305(key, nonce);
  const pt = cipher.decrypt(ct);
  return utf8Decode(pt);
}

// ────────────────────────────────────────────────────────────
// Sealed Sender (фаза 1) — анонімні до релея DM-конверти
// ────────────────────────────────────────────────────────────
// Звичайний DM шифрується статичним ECDH (мій×твій ключ), тому одержувач
// мусить знати відправника. Sealed ховає відправника від релея, отже й
// одержувач не може вивести статичний ключ -> ЕФЕМЕРНА пара (як Signal).
//
// blob = [ epk(32) | nonce(24) | ct ]
//   ct = XChaCha20( HKDF(ECDH(eph_priv, recipient_x25519), salt=epk),
//                   canonical({ sender, ts, payload, sig }) )
//   sig = Ed25519(seed) над canonical({ to, ts, payload })
// Одержувач: ECDH(його x25519, epk) -> ключ -> decrypt -> verify(sig).
// Релей бачить лише одноразовий epk + ct. Особа — всередині шифру.

const SEALED_INFO = utf8('morok-sealed-v1');

// canonicalJson() у цьому модулі повертає Uint8Array. Для sealed нам
// потрібен стабільний РЯДОК (його ж і шифруємо, і з нього робимо байти
// для підпису). РЕКУРСИВНА канонізація: JSON.stringify(obj, keys.sort())
// як replacer-масив працює лише для ключів ВЕРХНЬОГО рівня і спустошує
// вкладені об'єкти — тому власний обхід із сортуванням на кожному рівні.
function canonicalString(obj) {
  if (obj === null || typeof obj !== 'object') return JSON.stringify(obj);
  if (Array.isArray(obj)) return '[' + obj.map(canonicalString).join(',') + ']';
  const keys = Object.keys(obj).sort();
  return '{' + keys.map(
    (k) => JSON.stringify(k) + ':' + canonicalString(obj[k]),
  ).join(',') + '}';
}

function sealedSigMessage(to, ts, payload) {
  // LEGACY (v1) формат підпису — без epk. Лишається тільки для
  // ПЕРЕВІРКИ старих конвертів у польоті; нові конверти НЕ підписуються
  // цим форматом. Прибрати через кілька релізів після повного розкату.
  return utf8(canonicalString({ to, ts, payload }));
}

function sealedSigMessageV2(epkHex, to, ts, payload) {
  // v2: підпис додатково покриває ефемерний публічний ключ конверта.
  // Без epk внутрішній підпис автентифікує лише (to, ts, payload) —
  // тобто "хтось колись підписав цей текст для цього одержувача", а не
  // "цей конкретний шифротекст". Прив'язка до epk жорстко зв'язує
  // підпис саме з цим конвертом і відсікає re-wrap-сценарії, де чужий
  // підписаний payload пакується в новий конверт.
  return utf8(canonicalString({ epk: epkHex, to, ts, payload }));
}

export function sealedEncrypt({ seed, myPubkeyHex, peerPubkeyHex, payload, to, ts }) {
  const ephPriv = x25519.utils.randomPrivateKey();
  const ephPub = x25519.getPublicKey(ephPriv);

  const peerX25519Pub = x25519PubFromEd25519Pub(hexToBytes(peerPubkeyHex));
  const shared = x25519.getSharedSecret(ephPriv, peerX25519Pub);
  const key = hkdf(sha256, shared, ephPub, SEALED_INFO, 32);

  // v2: підпис прив'язаний до epk цього конверта (див. sealedSigMessageV2)
  const sig = sign(seed, sealedSigMessageV2(bytesToHex(ephPub), to, ts, payload)); // sign() вже повертає hex
  const inner = canonicalString({ sender: myPubkeyHex, ts, payload, sig, v: 2 });

  const nonce = randomBytes(24);
  const ct = xchacha20poly1305(key, nonce).encrypt(utf8(inner));
  const out = new Uint8Array(32 + 24 + ct.length);
  out.set(ephPub, 0);
  out.set(nonce, 32);
  out.set(ct, 56);

  const deleteKey = randomBytes(32);
  return {
    blobB64: bytesToBase64(out),
    deleteKeyHex: bytesToHex(deleteKey),
    deleteKeyHashHex: bytesToHex(sha256(deleteKey)),
  };
}

// ── morok.email: розшифрування поштового конверта (формат morok-mail-v1) ──
// БЕЗ перевірки підпису: автентичність гарантує relay (пошту формує лише
// SMTP-приймач релея). JSON.parse стійкий до будь-якого вмісту листа.
// Крос-перевірено Python(pynacl) ↔ цей код: збіг байт-у-байт.
const MAIL_INFO_V1 = utf8('morok-mail-v1');

export function mailOpen({ seed, blobB64 }) {
  const raw = base64ToBytes(blobB64);
  if (raw.length < 56 + 16) throw new Error('mail blob too short');
  const ephPub = raw.slice(0, 32);
  const nonce = raw.slice(32, 56);
  const ct = raw.slice(56);

  const myX25519Priv = x25519PrivFromSeed(seed);
  const shared = x25519.getSharedSecret(myX25519Priv, ephPub);
  const key = hkdf(sha256, shared, ephPub, MAIL_INFO_V1, 32);

  const json = utf8Decode(xchacha20poly1305(key, nonce).decrypt(ct));
  const payload = JSON.parse(json);
  if (payload.kind !== 'email') throw new Error('not an email payload');
  return payload; // { kind:'email', from, subject, date, text, html, attachments, spf, received_at }
}

// morok.email — ЗАШИФРУВАННЯ листа для внутрішньої пошти Morok↔Morok.
// Дзеркало mailOpen: той самий формат morok-mail-v1, шифруємо на pubkey
// адресата (його Ed25519 → Montgomery). Результат відкриє mailOpen у нього.
export function mailSeal({ recipientPubkeyHex, payload }) {
  const recipEdPub = hexToBytes(recipientPubkeyHex);
  const recipX = edwardsToMontgomeryPub(recipEdPub);
  const ephPriv = x25519.utils.randomPrivateKey();
  const ephPub = x25519.getPublicKey(ephPriv);
  const shared = x25519.getSharedSecret(ephPriv, recipX);
  const key = hkdf(sha256, shared, ephPub, MAIL_INFO_V1, 32);
  const nonce = randomBytes(24);
  const ct = xchacha20poly1305(key, nonce).encrypt(utf8(JSON.stringify(payload)));
  const blob = new Uint8Array(ephPub.length + nonce.length + ct.length);
  blob.set(ephPub, 0);
  blob.set(nonce, ephPub.length);
  blob.set(ct, ephPub.length + nonce.length);
  return bytesToBase64(blob);
}

export function sealedDecrypt({ seed, myPubkeyHex, blobB64, to }) {
  const raw = base64ToBytes(blobB64);
  if (raw.length < 56 + 16) throw new Error('sealed blob too short');
  const ephPub = raw.slice(0, 32);
  const nonce = raw.slice(32, 56);
  const ct = raw.slice(56);

  const myX25519Priv = x25519PrivFromSeed(seed);
  const shared = x25519.getSharedSecret(myX25519Priv, ephPub);
  const key = hkdf(sha256, shared, ephPub, SEALED_INFO, 32);

  const inner = JSON.parse(utf8Decode(xchacha20poly1305(key, nonce).decrypt(ct)));
  if (!inner.sender || !inner.sig || inner.payload === undefined || inner.ts === undefined) {
    throw new Error('sealed inner malformed');
  }
  const sigBytes = hexToBytes(inner.sig);
  const senderBytes = hexToBytes(inner.sender);
  // v2 (поточний формат, з epk у підписі); конверти з inner.v === 2
  // МУСЯТЬ пройти саме v2 — для них legacy-fallback не застосовується,
  // інакше прибирання epk із підпису не давало б нічого.
  let ok = ed25519.verify(
    sigBytes,
    sealedSigMessageV2(bytesToHex(ephPub), to, inner.ts, inner.payload),
    senderBytes,
  );
  // Legacy v1 (конверти, відправлені до апдейту, ще живі до 30 днів TTL).
  if (!ok && inner.v === undefined) {
    ok = ed25519.verify(
      sigBytes,
      sealedSigMessage(to, inner.ts, inner.payload),
      senderBytes,
    );
  }
  if (!ok) throw new Error('sealed signature invalid');
  return { senderPubkeyHex: inner.sender, ts: inner.ts, payload: inner.payload };
}

// ────────────────────────────────────────────────────────────
// Symmetric encrypt / decrypt (XChaCha20-Poly1305) — groups
// ────────────────────────────────────────────────────────────

/**
 * Generate a fresh 32-byte symmetric key (used as group_key).
 */
export function generateSymmetricKey() {
  return randomBytes(32);
}

/**
 * Encrypt arbitrary bytes with a known 32-byte symmetric key.
 * Output: nonce(24) ‖ ciphertext+tag, base64.
 */
// Ключ для локальних бекапів пошти, похідний від сіда.
// Доменно відокремлений (info="morok-mail-backup-v1") — це НЕ той ключ,
// що DM/mail/sealed. Формат зафіксовано назавжди.
const MAIL_BACKUP_INFO = utf8('morok-mail-backup-v1');
// Універсальний бекап пристрою (.morok): чати+групи+контакти+пошта+налаштування.
// ОКРЕМИЙ info-домен — файли пошти (.morokmail) і повні (.morok) несумісні навмисно.
const DEVICE_BACKUP_INFO = utf8('morok-backup-v1');
export function mailBackupKey(seed) {
  return hkdf(sha256, seed, new Uint8Array(0), MAIL_BACKUP_INFO, 32);
}

export function deviceBackupKey(seed) {
  return hkdf(sha256, seed, new Uint8Array(0), DEVICE_BACKUP_INFO, 32);
}

export function encryptWithKey(keyBytes, plaintextBytes) {
  if (keyBytes.length !== 32) throw new Error('key must be 32 bytes');
  const nonce = randomBytes(24);
  const cipher = xchacha20poly1305(keyBytes, nonce);
  const ct = cipher.encrypt(plaintextBytes);
  const out = new Uint8Array(24 + ct.length);
  out.set(nonce, 0);
  out.set(ct, 24);
  return bytesToBase64(out);
}

/**
 * Decrypt blob produced by encryptWithKey. Returns Uint8Array.
 * Throws if key wrong (auth tag fails).
 */
export function decryptWithKey(keyBytes, blobB64) {
  if (keyBytes.length !== 32) throw new Error('key must be 32 bytes');
  const raw = base64ToBytes(blobB64);
  if (raw.length < 40) throw new Error('blob too short');
  const nonce = raw.slice(0, 24);
  const ct = raw.slice(24);
  const cipher = xchacha20poly1305(keyBytes, nonce);
  return cipher.decrypt(ct);
}

/**
 * Convenience: encrypt a UTF-8 string with symmetric key. Returns base64 blob.
 */
export function encryptStringWithKey(keyBytes, plaintext) {
  return encryptWithKey(keyBytes, utf8(plaintext));
}

/**
 * Convenience: decrypt blob to UTF-8 string.
 */
export function decryptStringWithKey(keyBytes, blobB64) {
  return utf8Decode(decryptWithKey(keyBytes, blobB64));
}
